<a href="https://colab.research.google.com/github/arthik1699/sample_example-/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/wcj365/python-stats-dataviz/master/assignments/assignment_07_world_dev/world_devlopment_indicator.csv")

In [3]:
df.shape

(34954, 9)

In [4]:
df.head(10)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2002,876.327643,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
1,1,2003,928.191569,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
2,2,2004,925.704226,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
3,3,2005,1023.549501,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
4,4,2006,1078.907370,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
5,5,2007,1230.204790,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
6,6,2008,1273.787555,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
7,7,2009,1519.310737,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
8,8,2010,1710.762928,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
9,9,2011,1699.488110,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA

In [5]:
df.sample(10)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
19316,19316,2004,52.043000,SP.DYN.LE00.IN,SOM,Somalia,Sub-Saharan Africa,Low income,IDA
20212,20212,2002,71.089000,SP.DYN.LE00.IN,THA,Thailand,East Asia & Pacific,Upper middle income,IBRD
16842,16842,1984,65.887000,SP.DYN.LE00.IN,MDA,Moldova,Europe & Central Asia,Upper middle income,IBRD
11594,11594,1963,37.683000,SP.DYN.LE00.IN,CAF,Central African Republic,Sub-Saharan Africa,Low income,IDA
13719,13719,1961,46.279000,SP.DYN.LE00.IN,GHA,Ghana,Sub-Saharan Africa,Lower middle income,IDA
249,249,1997,22972.487859,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
4192,4192,2013,11062.558734,NY.GDP.PCAP.PP.CD,PRY,Paraguay,Latin America & Caribbean,Upper middle income,IBRD
17540,17540,2011,72.692000,SP.DYN.LE00.IN,NIC,Nicaragua,Latin America & Caribbean,Lower middle income,IDA
28619,28619,1981,26229.000000,SP.POP.TOTL,LIE,Liechtenstein,Europe & Central Asia,High income,Not classified
6456,6456,2003,7.900000,SH.STA.SUIC.P5,BFA,Burkina Faso,Sub-Saharan Africa,Low income,IDA

In [7]:
my_countries = ["USA", "IND", "CHN"]

df2 = df[df["Country Code"].isin(my_countries)]

df2.shape

(525, 9)

In [8]:
df2.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
1138,1138,1990,981.419207,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
1139,1139,1991,1093.566229,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
1140,1140,1992,1262.025483,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
1141,1141,1993,1454.491592,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
1142,1142,1994,1660.346880,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD

In [9]:
df2.tail()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
34359,34359,2017,325122128.0,SP.POP.TOTL,USA,United States,North America,High income,Not classified
34360,34360,2018,326838199.0,SP.POP.TOTL,USA,United States,North America,High income,Not classified
34361,34361,2019,328329953.0,SP.POP.TOTL,USA,United States,North America,High income,Not classified
34362,34362,2020,331501080.0,SP.POP.TOTL,USA,United States,North America,High income,Not classified
34363,34363,2021,331893745.0,SP.POP.TOTL,USA,United States,North America,High income,Not classified

In [12]:
df3 = df2.query('indicator == "SP.POP.TOTL" and Year == 2021')
df3

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
24146,24146,2021,1.412360e+09,SP.POP.TOTL,CHN,China,East Asia & Pacific,Upper middle income,IBRD
27112,27112,2021,1.393409e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
34363,34363,2021,3.318937e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified

In [17]:
fig = px.bar(df3, 
             x = "Country Name", 
             y ="value", 
             title = "2021 Population of USA, China and India", 
             color = "Country Name", 
             template = "plotly_dark")
fig.update_layout(showlegend = False)
fig.show()

In [21]:
fig = px.pie(df3, 
             names = "Country Name", 
             values ="value", 
             title = "2021 Population of USA, China and India", 
             color = "Country Name", 
             template = "plotly_dark")
#fig.update_layout(showlegend = True)
fig.update_traces
fig.show()